name: Demo Workflow

on: [push]

jobs:
  run-shell-commnad:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World" 
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commnad:
    runs-on: windows-latest
    needs: ['run-shell-commnad']
    steps:
      - name: Directpry PowerShell
        run: Get-Location
      - name: Direction Bash
        run: pwd
        shell: bash
